version: '3.8'

services:
  sleep-disorder-app:
    build: .
    container_name: sleep_disorder_container
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models
      - sqlite_data:/data
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - DATABASE_PATH=/data/sleep_disorder.db
    restart: unless-stopped

volumes:
  sqlite_data:
